export * from './instagram'
export * from './email'
export * from './menu-hamburguer'
export * from './whatsapp'
export * from './xmark'
export * from './chevron-left'
export * from './chevron-right'
